/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 .\public\models\Burger.glb 
*/

import React from "react";
import { useFrame, useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

export function Burger(props) {
  const group = React.useRef();
  const { scene, animations } = useGLTF("./models/Burger.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions } = useAnimations(animations, group);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature">
          <primitive object={nodes.Bone} />
          <skinnedMesh
            name="BreadBottom"
            geometry={nodes.BreadBottom.geometry}
            material={materials.Bread}
            skeleton={nodes.BreadBottom.skeleton}
          />
          <skinnedMesh
            name="BreadTop"
            geometry={nodes.BreadTop.geometry}
            material={materials.Bread}
            skeleton={nodes.BreadTop.skeleton}
          />
          <skinnedMesh
            name="Burger"
            geometry={nodes.Burger.geometry}
            material={materials["Material.001"]}
            skeleton={nodes.Burger.skeleton}
          />
          <skinnedMesh
            name="Cheese"
            geometry={nodes.Cheese.geometry}
            material={materials.Cheese}
            skeleton={nodes.Cheese.skeleton}
          />
        </group>
        <skinnedMesh
          name="Tomato001"
          geometry={nodes.Tomato001.geometry}
          material={materials.Tomato}
          skeleton={nodes.Tomato001.skeleton}
        />
        <skinnedMesh
          name="Tomato002"
          geometry={nodes.Tomato002.geometry}
          material={materials.Tomato}
          skeleton={nodes.Tomato002.skeleton}
        />
        <skinnedMesh
          name="Tomato003"
          geometry={nodes.Tomato003.geometry}
          material={materials.Tomato}
          skeleton={nodes.Tomato003.skeleton}
        />
        <skinnedMesh
          name="Tomato004"
          geometry={nodes.Tomato004.geometry}
          material={materials.Tomato}
          skeleton={nodes.Tomato004.skeleton}
        />
        <skinnedMesh
          name="Tomato005"
          geometry={nodes.Tomato005.geometry}
          material={materials.Tomato}
          skeleton={nodes.Tomato005.skeleton}
        />
      </group>
    </group>
  );
}

useGLTF.preload("./models/Burger.glb");
