/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 .\public\models\Chair.glb 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Chair(props) {
  const { scene } = useGLTF('./models/Chair.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.Root} />
      <skinnedMesh geometry={nodes.Back.geometry} material={materials.Back} skeleton={nodes.Back.skeleton} />
      <skinnedMesh geometry={nodes.Lap.geometry} material={materials.Lap} skeleton={nodes.Lap.skeleton} />
      <skinnedMesh geometry={nodes.Legs.geometry} material={materials.Legs} skeleton={nodes.Legs.skeleton} />
      <skinnedMesh geometry={nodes.Supports.geometry} material={materials.Supports} skeleton={nodes.Supports.skeleton} />
    </group>
  )
}

useGLTF.preload('./models/Chair.glb')
