/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 .\public\models\Computer.glb 
*/

import React, { useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Computer(props) {
  const group = React.useRef();
  const { nodes, materials, animations } = useGLTF("./models/Computer.glb");
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    actions["RGB"].play();
    // console.log(actions);
  }, []);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="Front"
          geometry={nodes.Front.geometry}
          material={materials.Black}
        />
        <mesh
          name="Roof"
          geometry={nodes.Roof.geometry}
          material={materials.Black}
        />
        <mesh
          name="WallL"
          geometry={nodes.WallL.geometry}
          material={materials.Black}
        />
        <mesh
          name="WallR"
          geometry={nodes.WallR.geometry}
          material={materials.Glass}
        />
        <mesh
          name="Back"
          geometry={nodes.Back.geometry}
          material={materials.Black}
        />
        <mesh
          name="Power"
          geometry={nodes.Power.geometry}
          material={materials.Black}
        />
        <mesh
          name="Plane"
          geometry={nodes.Plane.geometry}
          material={materials.Black}
        />
        <mesh
          name="Plane001"
          geometry={nodes.Plane001.geometry}
          material={materials.Black}
        />
        <group name="Cooler">
          <mesh
            name="Cube008"
            geometry={nodes.Cube008.geometry}
            material={materials.Black}
          />
          <mesh
            name="Cube008_1"
            geometry={nodes.Cube008_1.geometry}
            material={materials.RGB}
          />
        </group>
        <mesh
          name="GraphicCard"
          geometry={nodes.GraphicCard.geometry}
          material={materials.Black}
        />
        <mesh
          name="Motherboard"
          geometry={nodes.Motherboard.geometry}
          material={materials["Material.001"]}
        />
        <group name="Processor">
          <mesh
            name="Cube007"
            geometry={nodes.Cube007.geometry}
            material={materials.Black}
          />
          <mesh
            name="Cube007_1"
            geometry={nodes.Cube007_1.geometry}
            material={materials.RGB}
          />
        </group>
        <group name="Rams">
          <mesh
            name="Plane002"
            geometry={nodes.Plane002.geometry}
            material={materials.Black}
          />
          <mesh
            name="Plane002_1"
            geometry={nodes.Plane002_1.geometry}
            material={materials.RGB}
          />
        </group>
        <mesh
          name="Screw"
          geometry={nodes.Screw.geometry}
          material={materials.Black}
        />
        <mesh
          name="Screw001"
          geometry={nodes.Screw001.geometry}
          material={materials.Black}
        />
        <mesh
          name="PowerCord"
          geometry={nodes.PowerCord.geometry}
          material={nodes.PowerCord.material}
        />
      </group>
    </group>
  );
}

useGLTF.preload("./models/Computer.glb");
