/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 .\public\models\Desk.glb 
*/

import React from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

export function Desk(props) {
  const { scene } = useGLTF("./models/Desk.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.Root} />
      <skinnedMesh
        geometry={nodes.Back.geometry}
        material={materials.Back}
        skeleton={nodes.Back.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Drawer.geometry}
        material={materials.Drawer}
        skeleton={nodes.Drawer.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Drawer001.geometry}
        material={materials.Wooden}
        skeleton={nodes.Drawer001.skeleton}
      />
      <skinnedMesh
        geometry={nodes.DrawerSupport.geometry}
        material={materials.DrawerSupport}
        skeleton={nodes.DrawerSupport.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Legs.geometry}
        material={materials.Legs}
        skeleton={nodes.Legs.skeleton}
      />
      <skinnedMesh
        geometry={nodes.MiniSupports.geometry}
        material={materials.MiniSupports}
        skeleton={nodes.MiniSupports.skeleton}
      />
      <skinnedMesh
        geometry={nodes.MiniTop.geometry}
        material={materials.MiniTop}
        skeleton={nodes.MiniTop.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Sides.geometry}
        material={materials.Sides}
        skeleton={nodes.Sides.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Top.geometry}
        material={materials.Top}
        skeleton={nodes.Top.skeleton}
      />
    </group>
  );
}

useGLTF.preload("./models/Desk.glb");
