/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 .\public\models\Desk_Fan.glb 
*/

import React, { useEffect } from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

export function DeskFan(props) {
  const group = React.useRef();
  const { scene, animations } = useGLTF("./models/Desk_Fan.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    actions["Rotating"].play();
    // console.log(actions);
  }, []);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature">
          <primitive object={nodes.Body} />
          <skinnedMesh
            name="Base001"
            geometry={nodes.Base001.geometry}
            material={materials.BronzeMetalGuard}
            skeleton={nodes.Base001.skeleton}
          />
          <skinnedMesh
            name="Blades_1"
            geometry={nodes.Blades_1.geometry}
            material={materials.Blades}
            skeleton={nodes.Blades_1.skeleton}
          />
          <skinnedMesh
            name="Base"
            geometry={nodes.Base.geometry}
            material={materials.BronzeMetalGuard}
            skeleton={nodes.Base.skeleton}
          />
          <skinnedMesh
            name="Guard"
            geometry={nodes.Guard.geometry}
            material={materials.BronzeMetalGuard}
            skeleton={nodes.Guard.skeleton}
          />
          <skinnedMesh
            name="Guard001"
            geometry={nodes.Guard001.geometry}
            material={materials.BronzeMetalGuard}
            skeleton={nodes.Guard001.skeleton}
          />
          <skinnedMesh
            name="Guard002"
            geometry={nodes.Guard002.geometry}
            material={materials.BronzeMetalGuard}
            skeleton={nodes.Guard002.skeleton}
          />
          <skinnedMesh
            name="Joints"
            geometry={nodes.Joints.geometry}
            material={materials.BronzeMetalGuard}
            skeleton={nodes.Joints.skeleton}
          />
          <skinnedMesh
            name="Motor"
            geometry={nodes.Motor.geometry}
            material={materials.Blades}
            skeleton={nodes.Motor.skeleton}
          />
          <skinnedMesh
            name="Support"
            geometry={nodes.Support.geometry}
            material={materials.BronzeMetalGuard}
            skeleton={nodes.Support.skeleton}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("./models/Desk_Fan.glb");
