/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 .\public\models\MonitorPresentation.glb 
*/

import React from "react";
import { useGraph } from "@react-three/fiber";
import {  useGLTF } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

export function Monitor(props) {
  const { scene } = useGLTF("./models/MonitorPresentation.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  return (
    <group {...props} dispose={null}>
      {/* <Particles /> */}
      <primitive object={nodes.Bone} />
      <skinnedMesh
        geometry={nodes.Legs.geometry}
        material={materials.Monitor}
        skeleton={nodes.Legs.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Monitor.geometry}
        material={materials.Monitor}
        skeleton={nodes.Monitor.skeleton}
      />
      <skinnedMesh
        geometry={nodes.MonitorScreen.geometry}
        material={materials.Screen}
        skeleton={nodes.MonitorScreen.skeleton}
      />
    </group>
  );
}
useGLTF.preload("./models/MonitorPresentation.glb");
