/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 .\public\models\Mug.glb 
*/

import React from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

export function Mug(props) {
  const { scene } = useGLTF("./models/Mug.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.Bone} />
      <skinnedMesh
        geometry={nodes.Handle.geometry}
        material={materials.MugMaterial}
        skeleton={nodes.Handle.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Mug.geometry}
        material={materials.MugMaterial}
        skeleton={nodes.Mug.skeleton}
      />
    </group>
  );
}

useGLTF.preload("./models/Mug.glb");
