/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 .\public\models\Soda.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Soda(props) {
  const { nodes, materials } = useGLTF('./models/Soda.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Top.geometry} material={materials.MetalicSoda} />
      <mesh geometry={nodes.Bottom.geometry} material={materials.MetalicSoda} />
      <mesh geometry={nodes.Cap.geometry} material={materials.MetalicSoda} />
      <mesh geometry={nodes.Droplets.geometry} material={materials.SodaDroplet} />
      <mesh geometry={nodes.Mesh_3.geometry} material={materials.MetalicSoda} />
      <mesh geometry={nodes.Mesh_4.geometry} material={materials.SodaLabel} />
    </group>
  )
}

useGLTF.preload('./models/Soda.glb')
